"""add relationship

Revision ID: 86490ea356e0
Revises: b856b756c3c9
Create Date: 2021-04-12 12:49:09.523084

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '86490ea356e0'
down_revision = 'b856b756c3c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('password', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('movies_actors',
    sa.Column('actor_id', sa.Integer(), nullable=False),
    sa.Column('film_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['actors.id'], ),
    sa.ForeignKeyConstraint(['film_id'], ['films.id'], ),
    sa.PrimaryKeyConstraint('actor_id', 'film_id')
    )
    op.create_unique_constraint(None, 'actors', ['name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'actors', type_='unique')
    op.drop_table('movies_actors')
    op.drop_table('users')
    # ### end Alembic commands ###
